[phases.setup]
aptPkgs = ["...", "imagemagick", "libmagickwand-dev", "mlocate"]
[phases.build]
cmds = ["convert -version", "which convert", "locate libMagickWand.so", "mlocate libMagickWand.so", "..."]

